name: Get OIDC Token Workflow

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  call_reusable_workflow:
   uses: kymma-project/test-infra/.github/workflows/reusable-workflow.yml@refs/pull/10369/merge
