name: Get OIDC Token Workflow

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reusable Workflow
        uses: akiioto/test-infra/.github/workflows/reusable-workflow.yml@oidc_verify
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
